export const cities = [
  'Abuja, Nigeria',
  'Accra, Ghana',
  'Addis Ababa, Ethiopia',
  'Algiers, Algeria',
  'Antananarivo, Madagascar',
  'Asmara, Eritrea',
  'Bamako, Mali',
  'Bangui, Central African Republic',
  'Banjul, The Gambia',
  'Bissau, Guinea-Bissau',
  'Brazzaville, Republic of the Congo',
  'Cairo, Egypt',
  'Conakry, Guinea',
  'Dakar, Senegal',
  'Djibouti, Djibouti',
  'Dodoma, Tanzania',
  'Freetown, Sierra Leone',
  'Gaborone, Botswana',
  'Harare, Zimbabwe',
  'Kampala, Uganda',
  'Khartoum, Sudan',
  'Kigali, Rwanda',
  'Kinshasa, Democratic Republic of the Congo',
  'Libreville, Gabon',
  'Lilongwe, Malawi',
  'Lome, Togo',
  'Luanda, Angola',
  'Lusaka, Zambia',
  'Maputo, Mozambique',
  'Maseru, Lesotho',
  'Mbabane, Eswatini',
  'Mogadishu, Somalia',
  'Monrovia, Liberia',
  'Moroni, Comoros',
  "N'Djamena, Chad",
  'Nairobi, Kenya',
  'Niamey, Niger',
  'Nouakchott, Mauritania',
  'Ouagadougou, Burkina Faso',
  'Port Louis, Mauritius',
  'Praia, Cape Verde',
  'Pretoria, South Africa',
  'Rabat, Morocco',
  'Sao Tome, Sao Tome and Principe',
  'Tripoli, Libya',
  'Tunis, Tunisia',
  'Victoria, Seychelles',
  'Windhoek, Namibia',
  'Yaounde, Cameroon',
];
